### ISSUE TITLE
As a user, I want to log in using my GitHub account so that I can use the website's features while being able to access my GitHub information.

### ISSUE THREAD

**Issue by jeffbuonamici** [ivanb7/soen341group3#14]
**Priority:** 8

**Story points:** 3

**Description:** Allow users to login using their Github account. Then they can access the website and view their progress on group projects.

**Risks:** Privacy content being displayed on that the database.

**Comment by I-Dream-Of-Machines** [comment]
Task Breakdown: 

- [ ] Front-end log-in page [Jeff and Nadia]
- [ ] gitHub API for user features [Mattioco & Ivan]
- [ ] DB [Ivan]

**Comment by nathan-shumm** [comment]
Good good job!
