### ISSUE TITLE
As a TA, I want to view student profiles activity so that I can evaluate his participation to group projects.

### ISSUE THREAD

**Issue by jeffbuonamici** [ivanb7/soen341group3#15]
**Priority:** 5

**Story points:** 8

**Description:** As a TA, I want to view student profiles activity so that I can evaluate his participation to group projects. 

**Risk**: Displaying up to date user profile information to the TA.

**Comment by I-Dream-Of-Machines** [comment]
Task Breakdown:
- [ ] DB: Two user types
- [ ] Associate each user type with distinct functionality
- [ ] Parameters to measure student activity
- [ ] Front end to display student activity [Jeff + Nadia]
- [ ] Front end for TA functionality [Jeff + Nadia]
