### ISSUE TITLE
As a user, I want my GitHub information displayed on my profile page so other users can see who I am

### ISSUE THREAD

**Issue by jeffbuonamici** [ivanb7/soen341group3#16]
**Priority:** 1

**Story points:** 3

**Description:** Displaying profile and information such as name, id, followers, number of repos, company, location, bio, profile picture
**Risks:** no risks associated with this particular user story

**Comment by YousefAboElFoul** [comment]
Task Breakdown:

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ]
