### ISSUE TITLE
As a user, I want to access GitHub ativities so I can evaluate their participation to group projects

### ISSUE THREAD

**Issue by jeffbuonamici** [ivanb7/soen341group3#17]
**Priority:** 3

**Story points:** 3

**Description:**  Displaying activities on github such as participation in projects with number of commits, repositories, pulls... 

**Risks:** no risks associated with particular user story

**Comment by YousefAboElFoul** [comment]
Task Breakdown:

- [ ] Connect activity in classes/groups to GitHub

- [ ] evaluation criteria with GitHub
