### ISSUE TITLE
As a student, I want to message other users so that I can easily communicate with my classmates or my TA .

### ISSUE THREAD

**Issue by jeffbuonamici** [ivanb7/soen341group3#18]
**Story points:** 5

**Description:** As a use, I want to message other users so that I can easily communicate with my classmates or my TA. 
**Tasks:** The user will be able to select a user and send them a private message to begin/continue a private chat with the user they have selected. 

* Create a chat window to allow the user to send a message in (2hr) (done)
* Being able to find and select a user to chat with (1hr) 
* Have previous chats saved within the database and displayed in the current chat area (1hr)

**Priority:** Essential to the functionality of the private chat system, should be fully implemented and completed by the end of sprint 3. 
**Risk:** Making the chat instantaneous so that there is no delay between sending and receiving a message.

**Comment by YousefAboElFoul** [comment]
Task Breakdown:

- [ ] send chat to TAs/students/contacts

- [ ]  send chat to TAs within a group

**Comment by Mateuse** [comment]
done
