### ISSUE TITLE
As a user, I want to message a group of students so that I can reach out to a whole group at once

### ISSUE THREAD

**Issue by jeffbuonamici** [ivanb7/soen341group3#19]
**Story points:** 5

**Description:** As a user, I want to message a group of students so that I can reach out to a whole group at once. 
**Tasks:** The user will be able to select and save a group of users and send the group a private message to begin/continue a private chat with the selected group, while also being able to add people to the group at anytime.

* Select, add and remove people to the group chat at anytime. (1hr)
* Have previous chats saved within the database and displayed in the current chat area.(1hr)
* Create a chat window that allows the user to send/receive messages to/from other members in the group.(2hr) 

**Priority:** Essential to the functionality of the private group chat interface, should be fully implemented by the end of sprint 3. 
**Risk:** Making the chat instantaneous so that there is no delay between sending and receiving messages.

**Comment by YousefAboElFoul** [comment]
Task Breakdown:

- [ ] message all a particular group in a class

- [ ] select more than one group to send the same text or message

**Comment by nathan-shumm** [comment]
Good Job!
