### ISSUE TITLE
As a user, I want to upload documents to the chat, so that I can share files with my contacts.

### ISSUE THREAD

**Issue by jeffbuonamici** [ivanb7/soen341group3#21]
**Priority:** 1

**Story points:** 5

**Description:** This user story focuses on uploading documents on the chat interface.It is also limited by the amount of data that can be sent .

**Risks:** Server overload

**Comment by YousefAboElFoul** [comment]
Task Breakdown:

- [ ] upload different documents to chat

- [ ] ability to send links

- [ ] share files from one chat to another
