### ISSUE TITLE
As a TA, I want to be able to create a class so that communication with my students can be facilitated.

### ISSUE THREAD

**Issue by jeffbuonamici** [ivanb7/soen341group3#22]
**Priority:** 8

**Story points:** 2

**Description:** In order to create a class, the TA needs to fulfill two blanks text-area where you can specify the name of the course and a small description of the course. After completing the blanks, you click on the button "create the class" which will generate a small box panel with the information that you typing in. Also, in this panel, there will a button which you can click to and it will redirect in another page in order to communicate with the students and posts information.

**Risks:** Database errors with the creation of each class

**Comment by YousefAboElFoul** [comment]
Task Breakdown:

- [ ] Class with a particular set of students

- [ ] Add students to the class with being a prior contacty

**Comment by jeffbuonamici** [comment]
A class can be created and added to the database. The classes.ejs page also pulls classes from the database and displays them. But right now it's displaying all classes that are added to the database instead of classes specifically towards a user. I need sessions to be created in order to pull specific classes for a user.

**Comment by ivanb7** [comment]
Add: Ability to delete classes
