### ISSUE TITLE
 As a student, I want to be able to create a group so that I can work with a particular team of classmates.

### ISSUE THREAD

**Issue by jeffbuonamici** [ivanb7/soen341group3#24]
**Priority:** 3

**Story points:** 1

**Description:**  This user story focuses on group creations for students.If a class gives the ability for students to choose their teammates this is when this user story comes in handy.In other instances, one would have the ability to share past finals and midterms with other students without granting access to TAs and other students.

**Risks:** Creation of group might result in data complications

**Comment by YousefAboElFoul** [comment]
Task Breakdown:

- [ ] Creation of groups

- [ ] Selection of particular contacts

- [ ] Having the priority of the group created(as a TA)
