### ISSUE TITLE
As a TA, I want to be able to view the activity in subgroups (of my group) so that I can track their progress.

### ISSUE THREAD

**Issue by jeffbuonamici** [ivanb7/soen341group3#25]
**Priority:** 0

**Story points:** 0

**Description:** This user story gives administration to the TA so that he/she can view the students log activity.This can come in handy in group projects and class participation as well.

**Risks:** Not being able view due to database errors

**Comment by YousefAboElFoul** [comment]
Task Breakdown:

- [ ] Activity charts of students per group

- [ ] Activity charts of groups per class

- [ ] Activity of previous classes in comparison to current class
