### ISSUE TITLE
As a user, I want to post to my class so that everyone can see them.

### ISSUE THREAD

**Issue by jeffbuonamici** [ivanb7/soen341group3#26]
**Priority:** 1

**Story points:** 3

**Description:** This user story focuses on the posting to multiple groups at the same time.If a class contains more than one group then the ability to post to multiple groups at the same time is given by this user story.

**Risks:** Security issues might comes up

**Comment by YousefAboElFoul** [comment]
Task Breakdown:

- [ ] post documents for different groups in the same class at the same time

- [ ] post notifications for .....

- [ ] show and hide documents
