### ISSUE TITLE
As a user, I want to upload documents to the group page, so that the rest of the group can have access to them.

### ISSUE THREAD

**Issue by jeffbuonamici** [ivanb7/soen341group3#27]
**Priority:** 0

**Story points:** 2

**Description:** This user story focuses on uploading documents on group pages.This documents might be docx file, text file, pdf, etc. However, the amount of data to be uploaded on group will be limited.

**Risks:** not being able to control the amount of data being uploaded.

**Comment by YousefAboElFoul** [comment]
Task Breakdown:

- [ ] give access to uploaded documents for group members

- [ ] ability to upload specific documents(pdfs,excel,word-document etc..)

- [ ] show and hide uploaded documents
