### ISSUE TITLE
As a user, I want to comment on other users' posts so that we can discuss topics and ask questions

### ISSUE THREAD

**Issue by jeffbuonamici** [ivanb7/soen341group3#28]
**Priority:** 2

**Story points:** 1

**Description:** This user story focuses on the comment interface for posts in a group. A user can edit/delete his comment and this includes the one who posted the post and the one who commented on the post

**Risks:** One of the difficulties you might run into is getting the proper posts to show up for the appropriate group.

**Comment by YousefAboElFoul** [comment]
Task Breakdown:

- [ ] comment on TA/student posts

- [ ] notification on the commented psot

- [ ] enable and disable notification
