### ISSUE TITLE
As a user, I want to be able to receive a notification in the chat window when another user/group has messaged me so that I know someone has contacted me

### ISSUE THREAD

**Issue by Mateuse** [ivanb7/soen341group3#31]
**Story points:** 3

**Description:** As a user, I want to be able to receive a notification in the chat window when another user/group has messaged me so that I know someone has contacted me.
**Tasks:** A notification warning will appear on the chat area of the page to let the user know when they have been contacted. 
* The recipient of a message will be notified by the server that another user has sent them a message(2hr).

**Priority:** Low priority, not essential to the functionality of the chat, a nice feature to include should be finished at the end of the project if time permits.
**Risk:** Create a non-intrusive notification to prevent confusion of the user.

**Comment by YousefAboElFoul** [comment]
Task Breakdown:

- [ ] Chat window when receiving a message.

- [ ] Notification alert

- [ ]Make the window pop up
