### ISSUE TITLE
As a TA, I want to be able to assign TAs for a class so that there can be more than one grader

### ISSUE THREAD

**Issue by jeffbuonamici** [ivanb7/soen341group3#32]
**Story points:** 1

**Priority:** 1

**Description:** This user story focuses on assigning different TAs for a class.If a class has two groups, those two groups might be controlled by one TA or two .

**Risks:** Database overload

**Comment by YousefAboElFoul** [comment]
Task Breakdown:

- [ ] give priority to other TAs/users

- [ ] assign TAs for a specific  class/group

- [ ] giving multiple TAs the same task
