### ISSUE TITLE
As a user, I want to have a list of saved contacts so that I can easily select a person/group of people to chat with

### ISSUE THREAD

**Issue by Mateuse** [ivanb7/soen341group3#33]
**Story points:** 2

**Description:** As a user, I want to have a list of saved contacts so that I can easily select a person/group of people to chat with. 
Tasks: The user will have a list of contacts where they can save selected people/groups that they chat with often, so that they will be able to easily chat with the saved people again. 
* Create a contacts list for a user (1hr)

**Priority:** Medium priority, should be finished by the end of sprint 4 after the chat system has been implemented. 
**Risk:** Making sure that the contacts the user selects to add to the contact list is saved in their contact list.

**Comment by YousefAboElFoul** [comment]
Task Breakdown:

- [ ] add contacts and save them

- [ ] select all button 

- [ ] select by contact

**Comment by Mateuse** [comment]
Not Doing this
