### ISSUE TITLE
As a TA, I want to be able to control the privileges of my class members so that I can control who posts where

### ISSUE THREAD

**Issue by jeffbuonamici** [ivanb7/soen341group3#34]
**Story points:** 3

**Priority:** 1

**Description:** This user story focuses on the access granted for members on a group.For instance , you can delete posts, add members, delete/ban members and close/open the group/class.

**Risks:** Database errors when trying to control posts in a group

**Comment by YousefAboElFoul** [comment]
Task Breakdown:

- [ ] control for the TA

- [ ] deleting posts

- [ ] adding posts

- [ ] kicking and adding students
