### ISSUE TITLE
As a user, I want to join one or more classes so that I can communicate with other members of my class and the TA

### ISSUE THREAD

**Issue by jeffbuonamici** [ivanb7/soen341group3#35]
**Priority:** 5 

**Story points:** 2

**Description:** This user story gives the ability to join groups as a TA and as a student.As a user , who wants to join a class he/she must be given access by the admin of the group unless its open-to-all group.

**Risks:** Giving access to users for more than group might result in database errors.

**Comment by YousefAboElFoul** [comment]
Task Breakdown:

- [ ] ability to join different classes

- [ ] communication with members of the class

- [ ] communication with TA
