### ISSUE TITLE
As a user, I want to join one or more groups in a class so that I can communicate exclusively with members of my group

### ISSUE THREAD

**Issue by jeffbuonamici** [ivanb7/soen341group3#36]
**Priority:** 5

**Story points:** 2

**Description:**This user story focuses on the creation of the class within it creating groups and the ability to join the groups.It is with respect to both TAs and students.

**Comment by YousefAboElFoul** [comment]
Task Breakdown:

- [ ] communication within the group

- [ ] capability of joining different groups

- [ ] assigning it for both user protypes
