### ISSUE TITLE
As as user, I want to post to my group so that I can notify my group members of important information

### ISSUE THREAD

**Issue by jeffbuonamici** [ivanb7/soen341group3#37]
**Priority:** 1

**Story points:** 5

****Description**:** This user story focuses on the group posts for both TAs and students.Whenever there is an important message that someone wants to convey to a whole group including TAs , this user story corresponds to it.
**Risks:** Making the notification alerts work properly.

**Comment by YousefAboElFoul** [comment]
Task Breakdown:

- [ ] posts are listed into boxes

- [ ] comments on posts

- [ ] notification button
